export const ADD_ITEM = "ADD_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const UPDATE_ITEM = "UPDATE_ITEM";
export const EDIT_ITEM = "EDIT_ITEM";
export const SET_ACTIVE_ITEM_UNDEFINED = "SET_ACTIVE_ITEM_UNDEFINED";